# Generated by Django 4.2 on 2023-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.IntegerField(),
        ),
    ]
